### ISSUE TITLE
Move just-install to separate organization

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#209]
I would like to start a discussion about moving just-install to a separate organization and moving the registry to its own repository.

There are a couple of technical challenges to work out because just-install has the URL to registry hard-coded to point to this GitHub repository. I have an idea about how to do this in the least disruptive way but that will be detailed either in a comment to this issue or by opening another ticket in the issue tracker.

@guiweber I would also like to move https://github.com/guiweber/just-install-updater under the new just-install organization so that everything sits under the same roof.

Comments?

**Comment by guiweber** [comment]
I think it would make sense to do as you suggest. My only concern is that testing changes to the registry would be somewhat more tedious since it would not be embedded into Just-Install anymore. I feel that a way of configuring J-I to use the registry in another folder would be needed. Thoughts?

**Comment by geek1011** [comment]
I agree too

**Comment by geek1011** [comment]
I agree as well.

**Comment by lvillani** [comment]
@guiweber Yep, that would be needed. I will try to detail a migration plan in a separate ticket. Btw, I created the `just-install` organization and

**Comment by lvillani** [comment]
It's done. The repo is now under the `just-install` organization.
