### ISSUE TITLE
Move the registry to its own repository

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#210]
At the moment the registry is a file within just-install's own repository. This has a couple of shortcomings:

* Commits that improve just-install itself are interwined with commits that update the registry. This makes change tracking needlessly complicated.
* We have a test that checks that all entries in the registry are still reachable. These tests run even when we don't touch the registry itself. Also, these tests are flakey since they depend on network conditions, thus failing often.

I suggest that we move `just-install.json` to its own repository. This could also be the first step to move just-install to its own GitHub organization.

There are a couple of issues to overcome to guarantee a painless transition. These are due to bad design on my part since I didn't really expect `just-install` to be used outside of the company I work for 😅, i.e. `just-install` hard-codes the URL to the registry to point to this GitHub repository. Moving the registry to another repository would break every just-install deployment.

Also, since the registry will live in a different directory, we'll have to allow users (and developers) to specify the path to a local registry file, since we cannot rely on the "[autodiscovery](https://github.com/lvillani/just-install/blob/a9ca316be8e0ab05e5bbba53687b62e8b3e793f4/registry.go#L115-L119)" mechanism we have now.

#### Checklist

* [x] Copy the current registry to a new repository under the just-install organization.
* [x] Bump the registry version to `4` (a later step will explain why). Also change the `registrySupportedVersion` in the code to `4`.
* [x] Configure URL redirection for `registry.just-install.it` to point to the final registry location. The server must issue a `302 Found` with the destination URL.
* [x] Update just-install to use `registry.just-install.it`.
* [x] Add a command line argument to let users specify a path to the registry file to load. (DO NOT add support for loading arbitrary URLs, just local file paths).
* [x] Move registry checks to the separate repository and set-up an AppVeyor or Travis job to test installer reachability.
* [x] Release a new version of just-install that uses the new download URL and expects the new registry version.
* [x] Change `just-install.json` at the old location to be a minimal registry that only contains `{"version": 4}`. This will prompt users of old versions of just-install to upgrade to the new version.

The old `just-install.json` location must be available for at least one year starting from the day we release the new version that implements the changes described above. This will give users enough time to upgrade. (If the URL simply disappears, users will get a generic error instead of the upgrade prompt).

**Comment by lvillani** [comment]
@guiweber Any comments on the plan? I think we should also synchronize to make sure that new commits from just-install-updater go to the new repository once it goes online.

**Comment by geek1011** [comment]
I just want to say that github will redirect automatically raw urls for moved repos

**Comment by lvillani** [comment]
@geek1011 sure, but still, having the registry URL being under GitHub's domain (something that we don't control) is suboptimal, hence the move to a subdomain of `just-install.it`.

**Comment by geek1011** [comment]
I know. I am just saying this because it will make the upgrade process more seamless because the repo can be transferred sooner if the links will automatically redirect. This means the repo can be moved before the registry details are changed.

**Comment by geek1011** [comment]
Also, I am willing to help develop the command line argument option.

**Comment by lvillani** [comment]
I briefly tested whether RawGit works in case a GitHub repository is transferred. It seems to work fine, so I think I can accelerate the move of this repository to the org.

**Comment by lvillani** [comment]
All done!
