### ISSUE TITLE
There isn't version of 32 bits?

### ISSUE THREAD

**Issue by cazandobits** [just-install/just-install#226]
I, I'm a user of windows 7 32bits, is there any version of this program wich can run on 32 bits OS? (thanks!)

**Comment by lvillani** [comment]
Hey there! I just realized that our CI environment built x86-64 binaries even though we claim to support 32-bit systems. I pushed a new test build that you can try by running `msiexec.exe /i http://unstable.just-install.it`, can you try it and see if it works for you? (I don't have a Windows system at hand right now to test it myself, unfortunately).

**Comment by geek1011** [comment]
It works for me.

**Comment by lvillani** [comment]
Closing. It should be fixed in version 3.3.1. Please re-open if necessary.
