### ISSUE TITLE
Link to download EXE

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install#230]
There is currently no easy way to download just-install.exe standalone. http://static.just-install.it/release/stable/just-install-v3.3.0.exe cannot be accessed directly, and the other ways are hard to find.

**Comment by lvillani** [comment]
You mean adding a link to the exe on the website?

**Comment by geek1011** [comment]
Yes, and a way to get it. The s3 bucket cannot be directly accessed, there is no exe on bintray, and I am not aware of any other location.

On Feb 9, 2017 7:30 AM, Lorenzo Villani <notifications@github.com> wrote:

You mean adding a link to the exe on the website?

**Comment by lvillani** [comment]
Fixed in https://github.com/just-install/just-install.github.io/commit/cf500f67a6d0e73329c98c8d1b226b890e48c595
