### ISSUE TITLE
Ability to specify request headers and cookies in the registry

### ISSUE THREAD

**Issue by pgaskin** [just-install/just-install#231]
It is better if the app logic and the registry are kept separate. The code [here](https://github.com/just-install/just-install/blob/master/util.go#L176-L204) is related to apps, not just-install, so it would be better off in the registry. 

The way this could work is a new requestInfo object in each app in the registry, which contains a cookies array, and a headers array.

**Comment by geek1011** [comment]
I would be willing to work on this later this month, when I have more time.

**Comment by lvillani** [comment]
Sure, that's a great idea!

**Comment by lvillani** [comment]
While we are at it, let's investigate using a different HTTP client library that can also transparently work with proxy servers (for #220).

**Comment by lvillani** [comment]
I think we removed the need for this with policy changes and vendor changes in the upcoming version (e.g. we don't provide Oracle's JRE/JDK anymore). Can we close this for the time being?

(The new HTTP client _should_ support this use-case even though the registry doesn't expose it, so at least some of the work is already done. Architecturally it's the right thing to do, of course, but I don't think we have the explicit need for this right now).
