### ISSUE TITLE
Host just-install on Netlify

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install#239]
We could host just-install on Netlify. It is free, has free SSL, can deploy from a GitHub branch, can use custom domains for free, and can have multiple collaborators on the site.

**Comment by geek1011** [comment]
This would solve #212

**Comment by geek1011** [comment]
This could also solve just-install/registry#8 with a little bit of work.

**Comment by lvillani** [comment]
It would also go down with the next S3 outage :)

**Comment by geek1011** [comment]
Any ideas on this?

**Comment by guiweber** [comment]
I have personally never used their services, but it seems to me like it could be a simple solution to our SSL woes while providing a solid hosting solution.

**Comment by lvillani** [comment]
Aaaand, it's finally done!
