### ISSUE TITLE
Just-install customizer fatal error

### ISSUE THREAD

**Issue by eldertfrancke** [just-install/just-install#243]
"Error loading package list"

Error in Firefox console
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://rawgit.com/just-install/registry/master/just-install.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).
```

**Comment by geek1011** [comment]
Ok, thanks for reporting this. I'll look into this ASAP.

**Comment by geek1011** [comment]
I do not seem to have this issue in Firefox 52, Chrome, Opera, or Internet Explorer 11 on Windows. I have tried on Ubuntu and Windows 10. Please reopen this issue with more details if you still have this issue.

**Comment by eldertfrancke** [comment]
Sorry, I should have tested it before. The issue is solved by disabling the add-on: [HTTPS Everywhere](https://www.eff.org/https-everywhere).

**Comment by geek1011** [comment]
Ok. We are also thinking of switching to HTTPS completely quite soon.
