### ISSUE TITLE
Install remaining packages when one fails to install

### ISSUE THREAD

**Issue by guiweber** [just-install/just-install#245]
When installing several packages at once, just-install stops if one of the packages in the list fails to download/install. The remaining packages are not installed. It would be better if the remaining packages were installed anyway and a list of errors given when the process ends.

**Comment by geek1011** [comment]
I would suggest the errors are written to a log on the desktop by default instead, with an optional option to show the errors at the end of everything else instead. This is so people will still see the errors even when using a customized just-install exe launched directly.

There should also be a strict option for compatibility purposes which retains the current behaviour.

**Comment by mimi89999** [comment]
Any update on this? Recently `notepad++` started failing which resulted in incomplete deployments with many programs missing. One program missing would be be better than several missing. I think that _just-install_ should by default continue when a program fails or at least there should be an option for this.

**Comment by lvillani** [comment]
Should be fixed in 3.4.6. Closing.
