### ISSUE TITLE
Do not fail when msiexec.exe returns status 3010

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install#246]
When msiexec.exe returns error 3010, it means successful installation with a reboot required.

Related issue: just-install/registry#30

**Comment by geek1011** [comment]
cc @lvillani @guiweber

**Comment by geek1011** [comment]
Fixed. https://github.com/just-install/registry/issues/30#issuecomment-331731443

**Comment by geek1011** [comment]
@lvillani How do I do a release? Do I just tag it?

**Comment by guiweber** [comment]
@geek1011 is the user notified that a reboot is required at the very end of the just-install process or only when the program which returns status 3010 is installed? It would be nice to display something at the very end because if someone installs a large list of programs, he might miss the notice.

**Comment by geek1011** [comment]
@guiweber only when the program is installed. I didn't want to try to do too much because I wasn't able to test it because I was using Linux.
