### ISSUE TITLE
Update go version to 1.9.1 for CI

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install#247]
cc @lvillani @guiweber

**Comment by lvillani** [comment]
AppVeyor should already be using Go 1.9.0 (it's the default for their images), I updated Travis to use the same version.

**Comment by lvillani** [comment]
Closing this for now.

**Comment by geek1011** [comment]
@lvillani btw, it's actually `1.9.1`, not `1.9`.

**Comment by lvillani** [comment]
1.9.1 only brings a couple of security fixes, none of them seem to impact us. What are the benefits of deviating from the defaults provided by AppVeyor?

**Comment by geek1011** [comment]
@lvillani ok, I see your reasoning.
