### ISSUE TITLE
Ability to specify a checksum of the downloaded exe file

### ISSUE THREAD

**Issue by iilyak** [just-install/just-install#248]
It would be awesome if registry would support specification of a checksum for downloaded exe file.
```
   "checksum": "769474248a3897f4865817446f9a4a53",
   "checksum_type": "sha256",
```
OR by using https://github.com/multiformats/go-multihash

**Comment by Schokobecher** [comment]
Wouldn't this involve generating these values in the first place? Most software vendors don't offer hashes on their website.

What about updates to the files that aren't advertised on the site (Let's say App/Setup got updated to 1.0.1 without publishing new release info on the website that the updater parses) this would mark the file as invalid and file - right?

**Comment by iilyak** [comment]
The idea for checksum is to detect cases when vendor updates the file. The use case I am considering is as follows. 
1. We want to automate installation of development environment across the team members
2. We would download all dependencies on one machine 
3. We would manually calculate hashes and update `just-install.json` config file (https://github.com/just-install/registry/blob/master/just-install.json) to include the hashes
4. We would commit the `just-install` config file into our git repository
5. When new person joins the team we ask him/her to download `just-install` tool
6. We would point `just-install` to https://raw.githubusercontent.com/user/repository/branch/just-install.conf (we might need to download it first). It would be great if we just-install would be able to fetch the registry file over http.

> What about updates to the files that aren't advertised on the site (Let's say App/Setup got updated to 1.0.1 without publishing new release info on the website that the updater parses) this would mark the file as invalid and file - right?

That is the behavior we want for our use case. We don't want our dependencies to be different on different machines.

**Comment by lvillani** [comment]
I'm closing this for now since we don't have the resources to handle this process. Will re-evaluate in the future.
