### ISSUE TITLE
Zip extraction fails on certain files

### ISSUE THREAD

**Issue by nithinphilips** [just-install/just-install#251]
I was trying to create some new installation packages using just-install and I am having issues extracting certain zip files.

The file that failed was `sqldeveloper-17.4.0.355.2349-no-jre.zip` (it's the *Windows 32-bit/64-bit* download from
http://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/index.html) 

(*Oracle won't let you download these files without logging in first. I am serving local copies from a local server. So these packages can't really go into the main registry, but it would still be nice to get this working.*)

The installation log:

    2018/01/06 16:06:10 x86_64 - http://<local>/just-install/sqldeveloper-17.4.0.355.2349-no-jre.zip
    2018/01/06 16:06:11 Extracting to C:\tools
    2018/01/06 16:06:11 Unable to create destination: C:\tools\sqldeveloper\configuration\bundles.info

Screenshot of the file that failed: https://i.imgur.com/y8NxrTD.png

Package configuration:

    "sqldeveloper": {
      "installer": {
        "kind": "zip",
        "options": {
          "destination": "{{.SYSTEMDRIVE}}\\tools"
        },
        "x86": "http://<local>/just-install/sqldeveloper-{{.version}}-no-jre.zip"
      },
      "version": "17.4.0.355.2349"
    },

**Comment by geek1011** [comment]
Did you run just-install as an admin?

**Comment by nithinphilips** [comment]
Yep. I ran this as admin. I've tried running it from both Admin Command Prompt and Admin Powershell, both gave the same result. Btw, I'm on Windows 10 build 16299.192 ("Fall Creators Update").

**Comment by deguix** [comment]
Also applicable the pull-request from registry here: https://github.com/just-install/registry/pull/97. The subfolder doesn't get created first so the file extraction fails.

**Comment by geek1011** [comment]
After looking at https://github.com/just-install/just-install/blob/847b6d39839116694939cb519be5ce3f666d48bd/pkg/justinstall/util.go#L242, it seems like it is due to the way directories are created. IIRC, zip dir entries don't always need to be before the file entry, although most zip utilities store them that way. If you could upload an example of a zip file somewhere, I can take a look to see if this is the case.
