### ISSUE TITLE
Just install customizer

### ISSUE THREAD

**Issue by devjaa** [just-install/just-install#252]
![e5949fa4-a461-4c04-8526-47d2fa9ccdbc](https://user-images.githubusercontent.com/32819981/35746619-380281d8-07fc-11e8-8f66-27d73c6eea76.jpeg)

**Comment by geek1011** [comment]
I cannot reproduce this error. What browser are you using?

**Comment by geek1011** [comment]
As there has been no response for over a month, I'll close this issue now. If you still have this issue, feel free to reopen it with more details.
