### ISSUE TITLE
Sunsetting just-install

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#253]
I posted this on December 24th to our Gitter channel, since I didn't receive any feedback, I'm cross posting that message here.

Cc: @geek1011 @guiweber 

---

Hi there! I would like to reflect on the current status of just-install and its future.

As you can see, I no longer actively participate in j-i's discussions or development. I no longer have to work with Windows machines, and definitely won't have to do it in the near future. I don't even have a Windows-based gaming machine anymore. TL; DR: I don't have the time or motivation to work on just-install anymore.

As such, I would like to either transfer the ownership of the project to someone else or tell people to use Chocolatey instead.

What drove me to create just-install in the first place was the difficulty of installing Chocolatey on older Windows versions, but it seems to me that we reached the point it's no longer an issue.

The just-install.it domain name expires on May 15th, 2018. I'd like to find a new maintainer for just-install and transfer ownership before that date. If nobody steps up, I'll renew the domain for one more year to add a deprecation notice on the site and to the executable itself, then make all repositories read-only and archive them on GitHub. If after May 15th 2018 nobody steps up to revive the project I'll consider irrevocably sunsetting it. In such case, I'll release the just-install.it domain and the `just-install` namespace on GitHub after May 15th 2019, when the domain expires.

If anyone wants to step up, please let me know.

**Comment by geek1011** [comment]
Maybe @cyagon might like to, as he/she has contributed a lot to just-install recently?

As for myself, I do not use Windows much anymore, but I often reinstall my virtual machines which I use for testing and the occasional PowerPoint, and I like the simplicity of just-install. I am willing to continue to fix bugs, and keep it working (as I use it every few weeks myself), but I currently do not have much need or want of new features. As for time, I have been short on it recently as well.

I think just-install still has a few advantages over Chocolatey and Ninite. Firstly, there is the simplicity. Just-install has always been quite minimalistic and simple, and that is a huge advantage for maintenance and usage. Secondly, the just-install customizer which I contributed is really useful as a Ninite alternative, and is really easy for non-technical users to use, and has a larger selection of apps. Just-install is also more or less self-maintaining due to the updater. Thirdly, I find just-install to be faster, and slightly less buggy than Chocolatey. Fourthly, the registry is quite useful, as I have written scripts to download the latest installers of Windows programs I use, and cache them for quicker access later. Many similar things can be done with the registry.

**Comment by guiweber** [comment]
Sorry I didn't answer earlier, time has been short these past few months. I also like Just-Install for all the reasons listed by @geek1011. I think it still has its place.

I am committed to keep on maintaining the updater, fixing its bugs and making a few improvements, but unfortunately I don't really have time for more. I hope someone can be found.

**Comment by cyagon** [comment]
Since im (currently) jobless i have much time to contribute to just-install recently. But i could not maintain just-install itself since im still pretty much a rookie when it comes to programming.

Maybe someone can post something on reddit.com/r/sysadmin ?

**Comment by geek1011** [comment]
@cyagon But you would be fantastic at maintaining the registry, judging by your recent PRs.

**Comment by cyagon** [comment]
the registry? yes, but not just-install (the main software) itself

**Comment by seffyroff** [comment]
I use JI daily, and much like @cyagon am time-rich at the moment.  I wouldn't call myself a 'programmer' but I sure hack a lot.  I'd be interested in getting involved.  I would like to understand what the desired future state of JI is, the most requested features, and the missing pieces that will keep improvement and iteration flowing productively.  I'll have a poke around the issues and the code.  My own experience is that I wish I could easily define an install path for packages (maybe I can, it's probably an env var).  I dislike the Choco paid tier caching nag messages, and Scoop's limited catalog.  I'm not interested in any kind of dependency resolving.  I simply want the ability to install sofware, using as close to the vendor's original install package as possible, and have the option to do it in an automated fashion, or to do so from the shell quickly (so much faster than rummaging around arbitrary websites for downloads).

**Comment by JordyScript** [comment]
Hey :) I recently discovered JI and it is definitely something I find useful and much like @cyagon and @seffyroff would want to see it live on, but do not consider myself competent enough to lead out in this respect (far from it actually). Handing the project to someone even if not fully qualified, would at least leave the door open for the project to continue, so I hope that will happen. Am interested to know what will become of this project.

**Comment by geek1011** [comment]
@JordyScript This project will probably still continue to live on, as @guiweber, @cyagon,  and I still maintain it.

I am willing to take over the organization as owner, even though I don't use j-i as much anymore.

**Comment by lvillani** [comment]
The biggest fear that I have is that, in the long run, I risk becoming the bottleneck for maintaining just-install and the infrastructure surrounding it. Everything still works, for now, but given my other commitments we risk having important fixes delivered weeks after the fact. I would like to reach the point where I'm not a single-point-of-failure both for just-install itself and its infrastructure. So, in addition to sharing (or giving) ownership of the GitHub org, I need to find someone willing to gain control of the Netlify accounts, and the domain (and to pay OVH's bills).

Needless to say, during the transfer I'm willing to perform code reviews, just request my review in PRs.

@geek1011 I just made you co-owner of the org :)

**Comment by geek1011** [comment]
@lvillani If you give me access to the DNS for the domain, I can do any fixes needed. If OVH stops working, I can temporarily host it on my VPS. As for billing, I probably cannot do that.

P.S. What's on OVH anyways? AFAIK, the registry's on Netlify, the binaries are on bintray, CI's on appveyor, and I'm not sure where the updater is.

**Comment by lvillani** [comment]
@geek1011 OVH is the domain registrar for just-install.it, which is basically the only thing I'm currently being billed for (19€/yr). IIRC we're not using Bintray anymore and everything is being kindly hosted by Netlify (for free :heart:).

I can begin the long process of putting everything back under just-install.github.io (so as to remove the dependency on OVH, and me) if we agree to do so.

**Comment by cyagon** [comment]
Sounds good 👍

For the OVH dns control panel: @geek1011 just needs an ovh account, so you can transfer [the technical contact](https://docs.ovh.com/gb/en/customer/managing-contacts/) for "DNS Zone" to him. in this way he can manage the dns without technically owning the domain.

**Comment by geek1011** [comment]
@lvillani sounds good. We should keep the domain for now, but I just got an idea: we could have the github.io as the default registry, but with just-install.it as a fallback. We then continue to use just-install.it, but it we lose it, then we can just create a github repo for j-i and everything works fine with no changes to the client.

**Comment by geek1011** [comment]
sorry, pressed close and comment by accident

**Comment by seffyroff** [comment]
If it comes down to it I can stump up 19EUR for renewing the domain..

**Comment by lvillani** [comment]
@geek1011 Can you send me an email with your OVH "customer ID" so that I can add you as technical contact?

Btw, the domain is expiring on May 15th, but I'm going to renew it for another year at my expense.

**Comment by lvillani** [comment]
I'm not sure how to handle the move back to a `.github.io` subdomain for installers besides committing files to repos hosted on GitHub Pages (yuck!). I suspect that in order to host them on Netlify we still need the domain name, please correct me if I'm wrong.

**Comment by cyagon** [comment]
Github releases?

**Comment by cyagon** [comment]
@lvillani GitHub releases?

**Comment by lvillani** [comment]
@cyagon We have mnemonic aliases to install stable releases from the CLI in order to bootstrap a machine (e.g. `msiexec /i http://stable.just-install.it`). GitHub releases kinda defeats that (longer URLs, harder to remember), but I guess I'm just obsessed with reducing friction when bootstrapping a new machine (I consider those short URLs to be part of the "user interface" of j-i, so to speak).

**Comment by lvillani** [comment]
(I'm talking about a world in which `just-install.it` doesn't exist anymore, GitHub releases to decouple the project from Netlify is perfectly fine).

**Comment by geek1011** [comment]
@lvillani I've sent you an email. I also agree with your point about the domain. That is why I suggest using GitHub releases as a fallback if j-i cannot connect to the usual domain, but keep the usual domain for simplicity. If we do that, we should sign the registry to prevent anyone from taking over the domain to distribute malware if we don't renew the it.

Also, I have a really crazy idea which is to maybe support macOS. This would not be too much more complicated, as it would mostly consist of downloading a dmg, and either running a pkg or moving a .app. I find bouncing around different sites to download mac apps tedious. What do you think @lvillani?

**Comment by lvillani** [comment]
@geek1011 There's already [homebrew-cask](https://github.com/caskroom/homebrew-cask) for that, I use it every day 😉

**Comment by geek1011** [comment]
@lvillani oops, forgot that homebrew-cask exists. I only remembered about homebrew itself. My bad. :grin:

**Comment by geek1011** [comment]
As just-install is not going to disappear anytime soon, I think I'll close this issue to avoid confusion 
(for people passing by and looking at the issues). We can still continue to discuss here.
