### ISSUE TITLE
easy customizer: file name as options

### ISSUE THREAD

**Issue by dennyhalim** [just-install/just-install#262]
just a nice-to-have idea, 
instead of re-downloading each time we customized just-install.exe , why not let it read its own file name and use that as options.

example, if we want install firefox, just rename it to just-install_firefox.exe

**Comment by lvillani** [comment]
Unfortunately, I don't think we are going to implement this 😅

Encoding packages in the file name is very very brittle:

* What if the user renames the file?
* What if the browser mangles the file for whatever reason?
* What if someone adds so many packages and hits Windows' path length limit?

What seems a like a simple idea is fraught with edge cases and we don't have the necessary engineering resources to handle. The current mechanism is sufficiently reliable, at the cost of having to re-download the customiser every time.

**Comment by geek1011** [comment]
I agree with @lvillani .

Why don't you just download just-install and use a batch file (or whatever else) to append the correct options to the exe? That's really all the customizer does.
