### ISSUE TITLE
custom install directory?

### ISSUE THREAD

**Issue by jbschooley** [just-install/just-install#263]
I don't think this is implemented, if it isn't, would it be possible to implement passing a custom install directory? I have a small SSD along with a large hard drive and want to keep anything that isn't critical on the hard drive.

**Comment by FloatingShuYin** [comment]
I am also worried about this issue. I found that these software will be installed on my system disk.

**Comment by lvillani** [comment]
I'm afraid we won't be able to address this issue given the sheer amount of installer engines currently available on Windows and our limited man-power. I'm closing this issue but we may end up re-evaluating this decision in the future if there's enough demand for it.
