### ISSUE TITLE
just-install did not update

### ISSUE THREAD

**Issue by dennyhalim** [just-install/just-install#264]
got a problem.
re-running just-install did not downloading latest installer but it just re-run the old downloaded installer.

should it have somehow expired the old downloaded installer and re-download new installer?

thanks.

**Comment by geek1011** [comment]
This is hard due to fix due to the installer URLs remaining the same. Maybe we could also check the etag (if present)?

What do you think @lvillani?

**Comment by lvillani** [comment]
@geek1011 You mean adding the ETag field to the set of data that we "hash" to produce the filename that we use on disk?

**Comment by geek1011** [comment]
Yep. I'm also going to see if there are any similar headers we could check.

**Comment by dennyhalim** [comment]
just an idea...
why not hash the redirected url instead?

**Comment by geek1011** [comment]
@dennyhalim Not all installers redirect and it would also require an extra step to check the redirected URL (but it wouldn't be too hard to implement). Most newer web servers support ETags though.

**Comment by lvillani** [comment]
This is out of scope for now. Closing.
