### ISSUE TITLE
shouldn't customizer also install just-install?

### ISSUE THREAD

**Issue by dennyhalim** [just-install/just-install#265]
i tried the customizer and it did works and install other packages,
but it did not installing itself.

is this expected?
i think the customizer should also install itself.
at least let us choose just-install in the customizer.

thanks!

**Comment by geek1011** [comment]
This is expected.

There are two reasons why just-install does not install itself:
1. The customizer is meant to be an alternative to Ninite, which runs once without leaving itself behind.
2. j-i is not currently available as a j-i package.

@lvillani what do you think?

**Comment by lvillani** [comment]
I recall that we once had just-install itself in the registry, and that I removed it at some point. I can't remember why, though 😄

**Comment by lvillani** [comment]
I'm closing this ticket since there are no immediate plans to add such feature, but we may reconsider this choice in the future.
