### ISSUE TITLE
Revert to GOPATH, undo Go modules

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#277]
Go modules work just fine, but the tooling isn't ready yet and it makes developing just-install a pain.

Postpone Go modules migration until the ecosystem is ready.

See also: https://github.com/golang/go/issues/24661

**Comment by geek1011** [comment]
Maybe we could use both govendor and go modules?

**Comment by lvillani** [comment]
IIRC modules are mutually exclusive with $GOPATH.

**Comment by geek1011** [comment]
But modules can import from govendor's config, and modules with be used by tools that support them. That way, we can have govendor as the source of truth while still supporting modules.

**Comment by lvillani** [comment]
You can seed a module from govendor's config, once it's done, it lives a life of its own, IIRC. You can't easily build a module if it lives within $GOPATH (the compiler refuses to do so, unless you force it). 

Essentially only the core Go 1.11 build toolchain and GoLand understand modules at this point, everything else breaks in one way or another.

You have to jump through hoops to make both worlds coexist right now, and it doesn't really make much sense when 99% of the time you end up using only the good ol' govendor + GOPATH. Supporting both makes things unnecessarily complicated and will inevitably go out of sync.

I hate GOPATH. It's truly one of the worst and most confusing parts of having to deal with Go. I would like to fully embrace modules but it's not _that_ time yet. Pragmatism and limited time calls for GOPATH to become the default until the ecosystem is ready :)
