### ISSUE TITLE
Migrate back to just-install.github.io

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#281]
Action items following up on #267.

This will have the positive side effect of greatly simplifying our infrastructure by removing domain managment, Cloudflare, Netlify and a bunch of hackish CI jobs from the mix.

#### Checklist (WIP)

- [x] Release new version of just-install that fetches the registry from GitHub.
- [x] Publish unstable release as CI artifacts.
- [x] ~~Publish stable releases to GitHub Releases.~~
- [x] Publish stable releases to GitHub Pages.
- [x] Update install URL on website.
- [x] Setup redirects (301 permanent):
  - [x] https://just-install.it -> https://just-install.github.io
  - [x] https://registry.just-install.it -> https://raw.githubusercontent.com/just-install/registry/master/just-install.json (evaluate using GitHub Pages for this e.g. https://just-install.github.io/registry/just-install-v4.json).
  - [x] ~~https://stable.just-install.it and https://get.just-install.it -> Latest stable release~~ (cannot replace Netlify with OVH redirect since the latter doesn't support HTTPS and we end up breaking links). We'll have to maintain the Netlify infra and deploy simultaneously to both it and GH Pages until the cutoff date.)

#### Cleanup

- [x] Detach Cloudflare NS from domain.
- [x] Remove dnscontrol config.
- [x] Disable CI from infrastructure repo.
- [x] Remove Netlify configs.

**Comment by geek1011** [comment]
I think we should keep netlify, and use a subdomain of netlify. It will make it easy to move things around, as it allows more control than GitHub Pages.

As for beta/unstable, a CI job could be setup to build releases on every commit with the tag unstable.

**Comment by lvillani** [comment]
I would really like to slim down our infrastructure requirements to the bare minimum so that I can fit everything in my head :smile:.

Originally we went to Netlify to get TLS support for the most part. Now that GitHub supports TLS I don't a particular reason to keep Netlify around, besides some perceived flexibility gain (which we don't need right now?!).

I'd like to try to get rid of it in order to remove some moving parts I believe we don't need. I'm keeping everything around until I'm 100% sure that we don't need it for real.

**Comment by geek1011** [comment]
I agree with your first point, but for your second, I strongly believe we should keep netlify. I had quite a few issues when moving stuff around on my own site (first renaming pages, then getting let's encrypt to work properly on GH and my own server, and then SEO issues when moving the whole domain). By keeping netlify, we keep flexibility around redirects.
