### ISSUE TITLE
Just-install customizer fatal error

### ISSUE THREAD

**Issue by a925sw** [just-install/just-install#289]
Does not load anything, just errors. 

Error message:
````
0 error
````

**Comment by lvillani** [comment]
Hi! It seem to be working for me on Firefox (note to self: I'll try Edge and Chrome later). Which browser are you using right now?

**Comment by a925sw** [comment]
I apologize I should have looked into it more. The issue is on my end. It
appears rawgit.com is on some block lists so it wasn't loading due to that
fact. Again, my apologies.

**Comment by lvillani** [comment]
That's actually a problem on our end. We migrated away from rawgit some time ago. The registry is now being served by GitHub Pages. Plus, rawgit has been EOL'ed by its original maintainer. Good catch! I'll try to fix it soon-ish.

**Comment by lvillani** [comment]
Hi @a925sw, I removed all references to rawgit I could find. The issue should now be fixed.
