### ISSUE TITLE
Switch to go modules

### ISSUE THREAD

**Issue by geek1011** [just-install/just-install#295]
I think go modules and the tooling around it is mature enough to use now. I just switched most of my projects over, and it is significantly better. `go mod vendor` can be used to have a vendor dir for backwards compatibility and reproducibility, `gopls` works well in vscode, the `replace` directive is quite useful, and things seem quite a bit more polished than last time I tried it,

Doing this would simplify builds, make it easier to develop j-i, and simplify things in general.

cc @lvillani

**Comment by lvillani** [comment]
Aww yes! Looks like the next version of `vscode-go` should have OOB support for gopls. Tried it briefly on a couple of projects using modules and it seems to work way better than what we had before.

I'm taking the soft migration path by leveraging `go mod vendor`. Unlike last time, I'll wait a while before I remove the vendor folder and let AppVeyor cache dependencies in between builds.

**Comment by geek1011** [comment]
Yep. One of my favourite features of `gopls` is the refactoring/reference search doesn't thrash my disk for a few minutes searching everything I have. Also, the error checking is quite a bit faster.

As for `go mod vendor`, I'm using it for all my projects until I feel Project Athens is usable enough.

**Comment by lvillani** [comment]
I just decided to resurrect the stuff I did the first time I tried modules (i.e. let AppVeyor cache dependencies between builds). I dislike the idea of having hundreds of extraneous files in the repo :)
