### ISSUE TITLE
Using another location for installations

### ISSUE THREAD

**Issue by ancientaccount** [just-install/just-install#299]
Hello 👋

Is it possible to specify the hard disk on which I want to perform the installation or will they be on the hard disk where Windows is installed?

I'd like to use the tool for my school. However, computers are equipped with an SSD and a hard disk. I had the idea to make a first "software package" for the SSD and another for the hard drive.

**Comment by geek1011** [comment]
No, this currently isn't possible as it would mean needing to add additional options to the installer, which not installers support. It would also increase the complexity of just-install, which is meant to be as simple as possible.

A possible workaround would be to create a custom registry with additional command line options for the packages to control the installation location.
