### ISSUE TITLE
Add support for JetBrains NSIS installers

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#304]
Hello,

Some installers (mainly of JetBrains products) require a configuration file: https://github.com/just-install/registry/issues/115

Would it be possible for JustInstall to add support for creating those config files?

**Comment by lvillani** [comment]
It’s unlikely we’ll ever add support for creating such configuration files on the fly.

JetBrains products use NSIS and there’s _no reason at all_ for them to not support the standard NSIS method of performing silent installations. I played a bit with it and the only required parameter is `mode` and there’s no justification for being unable to pass it from the command line.

Their installer is broken and it adds to the pile of bespoke installers on Windows.

For now, I changed the registry entry to run the installer as-is, which means it will require user interaction. This the most we can do at the moment.

**Comment by mimi89999** [comment]
Could you please explain that to them on the issue tracker? I tried, but I think that I wasn't able to explain the issue clearly enough, so that they understand it.

**Comment by lvillani** [comment]
Re-opening since it's easier to just implement this (as a one-off workaround) rather than adding other mechanisms.

**Comment by mimi89999** [comment]
Can't it be done with #309?

**Comment by mimi89999** [comment]
Maybe it could be another installer kind.
