### ISSUE TITLE
Drop support for "zip" and "copy" installation methods

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#305]
Keep support for running installers inside ZIP containers though.

**Comment by mimi89999** [comment]
Why? There are currently 24 apps in the registry of `zip` kind and two `copy`. Some of them appear to be quite popular. While it would be best if upstream makes a proper installer, I don't think it is a necessary requirement to install an app.

**Comment by lvillani** [comment]
Yup, that was an oversight while I was refactoring that piece of code. In the end keeping support for zip containers still leaves a bunch of ugly code around, we gain nothing by removing zip and copy methods.
