### ISSUE TITLE
Automate package addition

### ISSUE THREAD

**Issue by servusDei2018** [just-install/just-install#316]
As this project grows large, merging pull requests from out-of-date forks will become an issue.

To fix this, I propose the following:

- Packages are added by a special issue template
- Packages added by this template have a "addition" tag
- The managers of this repository periodically sift through those additions, and if approved, add the "addition-approved" tag or close them after adding the "addition-rejected" tag
- After sifting through, a script is run which first clones the most recent copy of the repository, then goes through each open issue marked "addition-approved." It scrapes the data it needs (and posts a comment if there's an error), and then finally makes all the changes itself and opens a pull request.

Do this now and you'll avoid a lot of trouble in the future.

**Comment by servusDei2018** [comment]
@lvillani

**Comment by lvillani** [comment]
Given the low volume of pull requests it's more effort to create the automation than to process whatever incoming PRs we receive. I'm closing this issue for now, since I doubt we have the resources to pursue this, but will surely re-evaluate this in the future.
