### ISSUE TITLE
Semantics of "--force" command line flags are unclear

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#321]
At the moment the `--force` flag seems to cause all `Fetch` calls to overwrite all files we are attempting to fetch. Including the registry. E.g.: `just-install -f foo` will force-download both the registry and foo's installer. This is unexpected since we have the `update` action that force-downloads a fresh registry.

Rename `--force` to `--force-download` and make it apply only to installer downloads.

**Comment by mimi89999** [comment]
`--force-download` could be confused for re-attempting downloads after an error.

**Comment by lvillani** [comment]
We can probably try with something like `--redownload` or `--redownload-installer` or `--overwrite` (`--overwrite-installer`). `wget` uses "clobber" for this albeit I find the terminology a bit arcane.

**Comment by pgaskin** [comment]
I think all options like this should be prefixes with `--force` or something similar. But, for `--redownload`, why not use `--no-cache` or `--ignore-cache`.

**Comment by lvillani** [comment]
I'm going with `--ignore-cache`.
