### ISSUE TITLE
Logging to a file

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#324]
Hello,
It would be nice if it was possible to log to a file. I know that I can redirect output to a file with `just-install.exe app_name 1> C:\just-install-log.txt 2>&1`, but the file I get isn't quite readable because of the way the progress bar is being updated.

**Comment by mimi89999** [comment]
@lvillani Could I hear your opinion on that one? Can I add an option to disable the progress bar and print something else instead? How should I call that option?

**Comment by lvillani** [comment]
On Unix you would detect whether the program has a TTY attached, and automatically make a decision based on that. I don't know whether Windows has something similar. Speaking of command line switches: switches I've seen everything ranging from nothing (i.e. rely on the automatic behaviour alone) to `--noprogress` / `--no-progress` and stuff like that. I'm OK adding such options to the CLI.
