### ISSUE TITLE
Customizer lists the 64-bit architecture as x64_64

### ISSUE THREAD

**Issue by aaronfranke** [just-install/just-install#326]
https://just-install.github.io/customizer.html

The architecture for 32-bit says x86, and the architecture for 64-bit says x64_64. The latter is a typo, it should never be x64_64, it is either x86_64, or it can be shortened to x64.

P.S. Not related to this issue, but why is `dotnet` only 32-bit, and why isn't there .NET Core?

**Comment by geek1011** [comment]
That was indeed a typo, which I've now fixed. Thanks for reporting it.
