### ISSUE TITLE
Changing install directory

### ISSUE THREAD

**Issue by shane-gramlich** [just-install/just-install#327]
**Is there a supported way of changing the install directory for all packages? Specific packages?**

**Also, is there a way to change the install directory for 'just-install' itself?**

```
msiexec.exe /lv install-log.txt /i https://just-install.github.io/stable/just-install.msi TARGETDIR=%PATH%\to\just-install
```
The output from the above command demonstrates that TARGETDIR is successfully set but never used. It seems the 'WindowsPath' property is being used. However, the property is ignored if I try to pass it at the command-line:

```
msiexec.exe /lv install-log.txt /i https://just-install.github.io/stable/just-install.msi WindowsPath=%PATH%\to\just-install
```

**Comment by mimi89999** [comment]
Setting install path of packages in the registry is not supported by j-i. What do you need this feature for?

**Comment by lvillani** [comment]
There is currently no support for specifying different install paths. At the moment there are no plans to implement this feature. I'm closing this issue for now, but it may be re-evaluated in the future.
