### ISSUE TITLE
Trojan detected when creating custom installer

### ISSUE THREAD

**Issue by nixsee** [just-install/just-install#329]
Windows Defender tells me there is a trojan in this. Why?

![image](https://user-images.githubusercontent.com/24255237/86515904-baef0180-bdd9-11ea-9519-63948a970259.png)

**Comment by geek1011** [comment]
Probably a bad heuristic due to the nature of j-i, plus the fact it appends data to the end of the binary (i.e. it behaves like a dropper). I'll see what I can do about this.

**Comment by geek1011** [comment]
J-i itself is fine: https://www.virustotal.com/gui/file/0b8e771369c8016e459d9318124bfa50251e4ee4aa57fd716006a7e35c931cc9/detection.

**Comment by nixsee** [comment]
I'm not entirely sure what that means - I just tried to download this link: 

https://just-install.github.io/customizer.html#7zip,bitwarden,autohotkey,calibre,cryptomator,discord,etcher,everything-search,filezilla,flash-player,google-drive,notepad++,python3,qbittorrent,rufus,sharex,sharpkeys,sumatrapdf,vcredist-2005,vcredist-2008,vcredist-2012,vcredist-2010,vcredist-2013,vcredist-2015,vcredist-2017,vcredist-2019,visual-studio-code,vlc,windirstat,winscp,wox

**Comment by mimi89999** [comment]
With your installer: https://www.virustotal.com/gui/file/2c7b5e2ccbf85ef6f9db89d11f21e30d07a32fff858fae944ec43357ee3f5f41/detection

The signature shows it is heuristic, not a particular malware that was found: https://malwaretips.com/blogs/remove-trojanwin32fuery-acl/

**Comment by nixsee** [comment]
Interesting - not sure why Windows Defender blocks it when it doesnt on Virus Total. Anyway, it looks safe enough to use...
