### ISSUE TITLE
Backport appx and jetbrains-nsis and release 3.4.8

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#331]
See also #328

**Comment by lvillani** [comment]
@mimi89999 3.4.8 is up!

**Comment by mimi89999** [comment]
Thanks a lot for https://github.com/just-install/just-install/releases/tag/v3.4.8!

**Comment by mimi89999** [comment]
@lvillani The website still has `3.4.7`.

**Comment by lvillani** [comment]
Darn, the binary is actually a 3.4.8. I forgot to bump files that are used to embed the version number... I forced-pushed a bunch of stuff to make things right (I know...😅)

**Comment by mimi89999** [comment]
Is that version the latest master or `3.4.7` with installers?

**Comment by mimi89999** [comment]
If it's latest master, then we also can add shell links.

**Comment by lvillani** [comment]
It's not the latest master, it would be too risky to release the latest master as-is. Current master will become `4.0.0` some time in the future.
