### ISSUE TITLE
Feature Request: Faster download with piece split 

### ISSUE THREAD

**Issue by jascodes** [just-install/just-install#336]
Some of packages are downloading slow due to speed from server. But if the download is split into multiple pieces the download speed can be improved.

**Comment by mimi89999** [comment]
I doubt that it would help. Slow servers are usually the only servers with a certain file and mirrors and anycast servers are usually run by big orgs and they can serve resources much faster that any user could be downloading.

In what case could this help?

**Comment by jascodes** [comment]
I meant just like download manager which split the same file and download it in pieces to make download fast.Scoop implemented upon my request and it works like magic. https://github.com/lukesampson/scoop/issues/2306

**Comment by mimi89999** [comment]
Could you please give examples of entries/installers that are in the registry or that you plan to add for which you see a download speed improvement?

**Comment by lvillani** [comment]
Thanks for your feature request. There are currently no plans to implement a download manager or integrate an external one (e.g. aria2c). Even though it seems a simple feature it adds up development and testing overhead that we cannot bear at the moment. Closing, will re-evaluate at a later time.
