### ISSUE TITLE
Feature Req: just-install search

### ISSUE THREAD

**Issue by jascodes** [just-install/just-install#337]
for searching repo

**Comment by mimi89999** [comment]
Just-install doesn't have entry descriptions and the registry doesn't have that many apps. I doubt that searching through entry names would be very useful.

**Comment by jascodes** [comment]
@mimi89999 Well the list is gonna grow, infact I will be putting on in and that ain't gonna be last one. Anyhow I don't care about description, I am looking for name of the app. So lets say I want to install epic launcher. I just wanna search epic keyword to get the app name. Right now have to look it up.

**Comment by lvillani** [comment]
You can achieve the same by running `just-install.exe | findstr epic`. No need to implement a custom command 😉. Closing.

**Comment by pgaskin** [comment]
There's also the just-install customizer.
