### ISSUE TITLE
Question: Backup and restore

### ISSUE THREAD

**Issue by jascodes** [just-install/just-install#338]
Is there any file which have record of installed programs? any maybe commands to restore?

**Comment by mimi89999** [comment]
Just-install doesn't record install logs nor keeps a list of installed apps.

**Comment by jascodes** [comment]
Hmm... don't you think its helpful? I would say keep it simple and have local copy of registry have installed key true or false. That should be enough.

**Comment by lvillani** [comment]
The correct way would be to query the system whether a package is installed or not. If we store a flag ourselves it would get out of sync with the system really quickly, to the point of being essentially worthless. There are currently no plans to implement this feature. I'm closing this issue for now. It may be re-evaluated in the future.
