### ISSUE TITLE
Reconsider interactive installers

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#342]
Having interactive installers is good for some users because at least they don't have to download and launch them. However it's against j-i logic and is bad for admins and automatic deployments. They must be extra careful not to add them to the deployment list because the deployment will just hang. They are neither marked on the website nor in the list. Only during the deployment there is a warning printed.

It is possible to mark them on the website, list and add an option to fail on interactive installers (because some apps might become interactive). However, I think that it's not the way to go. We should convince the devs to make noninteractive installers and not include interactive ones in j-i.

**Comment by lvillani** [comment]
After thinking about this for a while, I agree with you. We should remove support for interactive installers within j-i and also update our registry contribution policies.

See also: https://github.com/just-install/registry/issues/240

**Comment by lvillani** [comment]
Please note that I prefer to remove support for interactive installers altogether and refuse their addition to the registry. I'm leaning on the side of lessening our support burden as much as possible since we don't have the manpower to handle these special cases.
