### ISSUE TITLE
How do I update packages?

### ISSUE THREAD

**Issue by VladPutinEu** [just-install/just-install#345]
Does just-install have a feature that updates packages after I have installed them? If so, how do I use that feature?

**Comment by mimi89999** [comment]
Hello,
just-install does not support updating packages, however running `just-install package` will run the new installer and that should update your package.

**Comment by VladPutinEu** [comment]
When I run that it says `WARNING: Unknown package package`

**Comment by mimi89999** [comment]
Replace `package` with the name of your package. I meant use just-install as if you were installing the app for the first time.

**Comment by VladPutinEu** [comment]
Is there a feature that I can use the check which apps are out of date?

**Comment by mimi89999** [comment]
> Is there a feature that I can use the check which apps are out of date or do I have to do it manually?

No

**Comment by VladPutinEu** [comment]
Thanks for the help. I'm looking for a package manager that lets me easily update apps. I guess I must go back to looking for a package manager.
