### ISSUE TITLE
Skip if already upto date

### ISSUE THREAD

**Issue by danielsherratt** [just-install/just-install#346]
Hi there, is it possible for the app to skip the package if it already has the latest installed? Daniel

**Comment by danielsherratt** [comment]
I suspect it wont be possible as some of the versions are "latest", it would also mean having to add a installed path in so the program could check it, which you don't want to do for every package as it would be very time consuming

**Comment by mimi89999** [comment]
j-i also doesn't save a list of installed packages, so it can't know if a package was installed.

**Comment by danielsherratt** [comment]
Ok thanks!, I've altered my script to check every 30days, I think its safe to assume there will be an update monthly for Notepad++ and other various software
