### ISSUE TITLE
ERROR just-install eclipse-java 

### ISSUE THREAD

**Issue by iizquierdo** [just-install/just-install#349]
When running the just-install eclipse-java command, the following error is returned:

```
C:\WINDOWS\system32>just-install eclipse-java
2022/07/27 11:02:27 x86_64 - http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-win32-x86_64.zip
2022/07/27 11:02:28 Unexpected HTTP response code. Wanted 200 but got 404
```

**Comment by lvillani** [comment]
This project is being kept for archival purposes only. I suggest you to switch to [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/). We'll add a notice to the website and archive the main repository in the coming weeks.
